"""
Model subsystem specifications.

The model subsystem defines the declarative structure of an artifact
model.

Models describe what may be built. They do not perform builds.

A model consists of:

    Model
        A complete artifact model definition.

    Feature
        An optional capability supported by a model.

    Stage
        One resumable step in the model workflow.

    Product
        A filesystem work product produced by a stage.

Features may affect a model in different ways. A feature may enable a
stage, modify the behavior of an existing stage, or do both.

For example, a circular model might support optional features such as:

    artwork
        Adds printable artwork and may enable artwork-processing stages.

    labels
        Modifies artifact geometry and enables label-building stages.

    ridges
        Modifies artifact geometry produced by an existing stage.

    hanger
        Modifies artifact geometry produced by an existing stage.

    magnet
        Modifies artifact geometry produced by an existing stage.

Execution, configuration resolution, feature interpretation, dependency
resolution, stage validity, and artifact materialization belong to other
subsystems.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# =========================================================
# Products
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class ProductSpec:
    """
    Define a filesystem work product produced by a stage.

    The path is relative to the artifact working directory.

    Product filenames are intentionally artifact-independent because
    every artifact receives its own working directory.

    Products describe persistent filesystem outputs that participate in
    determining whether a stage has completed successfully.

    A stage may create additional temporary or diagnostic files that are
    not declared as products.
    """

    name: str

    path: str

    description: str = ""


# =========================================================
# Features
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class FeatureSpec:
    """
    Define an optional capability supported by a model.

    Features are declarative capabilities. Enabling a feature may alter
    model geometry, enable one or more workflow stages, affect generated
    products, or otherwise change model-specific behavior.

    FeatureSpec does not define how a feature is implemented. That
    behavior belongs to the model implementation.

    A model may be valid with none of its optional features enabled.
    """

    name: str

    description: str = ""


# =========================================================
# Stages
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class StageSpec:
    """
    Define one resumable stage in a model workflow.

    A stage is the smallest unit of work that the build system may
    independently determine to be current, stale, or incomplete.

    Dependencies identify other stages that must be satisfied before
    this stage may execute.

    Required features identify optional model features that must be
    enabled for this stage to participate in an artifact workflow.

    An empty required-features tuple means that the stage participates
    regardless of which optional features are enabled.

    A feature does not need to appear in requires_features merely
    because it affects the behavior of a stage. For example, a hanger
    feature may modify the geometry produced by an always-present holder
    stage without being required for that stage.

    Parameters identify resolved artifact configuration values whose
    values materially affect the products generated by this stage.

    Parameter names refer to the resolved artifact configuration, not
    to a particular configuration tier or TOML location. A resolved
    value may originate from master defaults, workspace overrides, or
    artifact-specific overrides.

    Stage validity should therefore depend on the resolved parameter
    values consumed by the stage rather than on where those values
    originated.

    Products describe persistent filesystem outputs whose existence and
    validity participate in determining whether the stage is satisfied.
    """

    name: str

    description: str = ""

    dependencies: tuple[str, ...] = ()

    requires_features: tuple[str, ...] = ()

    parameters: tuple[str, ...] = ()

    products: tuple[ProductSpec, ...] = ()


# =========================================================
# Models
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class ModelSpec:
    """
    Define an artifact model.

    A model describes the capabilities and workflow used to transform
    an artifact definition into a final printable 3MF file.

    Features identify the optional capabilities supported by the model.

    Stages define the model's complete potential workflow. Individual
    artifact workflows may contain only a subset of those stages when
    stages depend on optional features that are not enabled.

    ModelSpec is declarative. It does not execute stages, interpret
    feature behavior, resolve configuration, determine stage validity,
    or manipulate artifact files.
    """

    name: str

    title: str

    description: str = ""

    features: tuple[FeatureSpec, ...] = field(
        default_factory=tuple,
    )

    stages: tuple[StageSpec, ...] = field(
        default_factory=tuple,
    )

    defined_in: str | None = None
