"""
Model subsystem specifications.

The model subsystem defines the declarative structure of an artifact
model.

Models describe what may be built. They do not describe a particular
artifact and they do not perform builds.

A model consists of:

    Model
        A complete artifact model definition.

    Feature
        An optional capability or behavior supported by a model.

    Stage
        One resumable step in the model workflow.

    Product
        A persistent filesystem work product produced by a stage.

Artifact content and configuration are separate from model
specifications.

For example, an artifact may contain zero, one, or many artwork
instances. Each artwork instance may have its own source, size,
position, and rotation. Those instances belong to artifact
configuration rather than ModelSpec or FeatureSpec.

Features describe optional model behavior. For example, a circular
model might support features such as:

    ridge
        Adds raised ridge geometry to the artifact.

    labels
        Adds printable lettering to the artifact.

    hanger
        Adds hanger geometry to the artifact.

    magnet
        Adds an internal magnet cavity to the artifact.

    fill
        Adds background geometry around artwork.

A feature may enable a stage, modify the behavior of an existing stage,
or do both.

Execution, artifact configuration, configuration resolution, feature
interpretation, dependency resolution, stage validity, and artifact
materialization belong to other subsystems.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# =========================================================
# Products
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class ProductSpec:
    """
    Define a persistent filesystem work product produced by a stage.

    The path is relative to the artifact working directory.

    Product filenames are intentionally artifact-independent because
    every artifact receives its own working directory.

    Products describe persistent filesystem outputs that participate in
    determining whether a stage has completed successfully.

    A stage may create additional temporary or diagnostic files that are
    not declared as products.

    Products may include intermediate build results as well as final
    printable geometry. The important distinction is that a declared
    product participates in the resumable build contract of its stage.
    """

    name: str

    path: str

    description: str = ""


# =========================================================
# Features
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class FeatureSpec:
    """
    Define an optional capability or behavior supported by a model.

    Features are declarative capabilities. Enabling a feature may alter
    model geometry, enable one or more workflow stages, affect generated
    products, or otherwise change model-specific behavior.

    Features describe model behavior rather than artifact content.

    For example, an artifact containing four artwork instances does not
    contain four artwork features. The artwork instances are artifact
    configuration. Features instead describe optional behaviors such as
    adding a ridge, hanger, magnet cavity, labels, or background fill.

    FeatureSpec does not define how a feature is implemented. That
    behavior belongs to the model implementation.

    A model may be valid with none of its optional features enabled.
    """

    name: str

    description: str = ""


# =========================================================
# Stages
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class StageSpec:
    """
    Define one resumable stage in a model workflow.

    A stage is the smallest unit of work that the build system may
    independently determine to be current, stale, or incomplete.

    Dependencies identify other stages that must be satisfied before
    this stage may execute.

    Required features identify optional model features that must be
    enabled for this stage to participate in an artifact workflow.

    An empty required-features tuple means that the stage participates
    regardless of which optional features are enabled.

    A feature does not need to appear in requires_features merely
    because it affects the behavior of a stage. For example, a hanger
    feature may modify geometry produced by an always-present base stage
    without being required for that stage.

    Parameters identify resolved values consumed by the stage whose
    values materially affect the products generated by that stage.

    Resolved values may be configured directly or derived from other
    configuration values, model geometry, enabled features, or artifact
    content.

    Parameter names refer to the resolved artifact configuration rather
    than to a particular configuration tier or TOML location. A resolved
    value may originate from master defaults, workspace overrides,
    artifact-specific overrides, or derivation performed during
    configuration resolution.

    Stage validity should therefore depend on the resolved values
    consumed by the stage rather than on where those values originated.

    Products describe persistent filesystem outputs whose existence and
    validity participate in determining whether the stage is satisfied.
    """

    name: str

    description: str = ""

    dependencies: tuple[str, ...] = ()

    requires_features: tuple[str, ...] = ()

    parameters: tuple[str, ...] = ()

    products: tuple[ProductSpec, ...] = ()


# =========================================================
# Models
# =========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class ModelSpec:
    """
    Define an artifact model.

    A model describes the capabilities and workflow used to transform
    an artifact definition into a final printable 3MF file.

    A model describes a kind of artifact rather than a particular
    artifact instance.

    Artifact-specific content belongs to artifact configuration. For
    example, configuration may describe zero, one, or many artwork
    instances and the placement, size, and rotation of each instance.

    Features identify optional capabilities or behaviors supported by
    the model.

    Stages define the model's complete potential workflow. Individual
    artifact workflows may contain only a subset of those stages when
    stages depend on optional features that are not enabled.

    ModelSpec is declarative. It does not execute stages, describe
    individual artwork instances, interpret feature behavior, resolve
    configuration, determine stage validity, or manipulate artifact
    files.
    """

    name: str

    title: str

    description: str = ""

    features: tuple[FeatureSpec, ...] = field(
        default_factory=tuple,
    )

    stages: tuple[StageSpec, ...] = field(
        default_factory=tuple,
    )

    defined_in: str | None = None
