[parameters]

artwork_size = 100
artwork_pixels = 1024
artwork_raise = 1.0

artwork_envelope_mode = "shrink-wrap"

artwork_min_island_area = 34
artwork_island_connectivity = 8

# --------------
# Optional standalone Loop Feature.
# loop_inner_diameter == 0 disables Loop participation.

loop_inner_diameter = 0.0
loop_width = 1.0
loop_position = 0

# loop_raise = 1.0  # defaults to artwork_raise
# loop_color = "white" # defaults to outer_ridge color, or color at point of attachment

# --------------
# Optional standalone Base Feature.
# artwork_base_raise == 0 disables Base participation.

artwork_base_raise = 0.0

# artwork_base_color = "white"  # derived from Loop or Artwork attachment color


# --------------
# Physical width of the optional standalone Artwork Outer Ridge.
#
# Zero disables the Outer Ridge.
# Positive width enables the Outer Ridge.
#

artwork_outer_ridge_width = 0.0
# artwork_outer_ridge_raise = 1.0 # defaults to artwork_raise
# artwork_outer_ridge_color = "black"  # defaults to attachment color at loop_position


# --------------
# Optional standalone Hole Feature.
# artwork_hole_diameter == 0 disables Hole participation.

artwork_hole_diameter = 0.0
artwork_hole_position = 0
artwork_hole_edge_distance = 0.4
