[parameters]

artwork_size = 100
artwork_pixels = 1024
artwork_raise = 1.0

artwork_envelope_mode = "shrink-wrap"

artwork_min_island_area = 34
artwork_island_connectivity = 8

# Optional standalone Loop Feature.
# loop_inner_diameter == 0 disables Loop participation.

loop_inner_diameter = 0.0
loop_width = 1.0
loop_position = 0

# loop_raise = 1.0  # defaults to artwork_raise
# loop_color = "white" # defaults to outer_ridge color, or color at point of attachment
